services:
  techreochallenge_web:
    build:
      context: techreo-challenge-web
      dockerfile: Dockerfile
    container_name: techreo-challenge-web
    depends_on:
      - techreochallenge_api
    ports:
      - "4200:80"
    networks:
      - techreo-challenge-network

  techreochallenge_api:
    build:
      context: .
      dockerfile: TechreoChallenge.Api/Dockerfile
    container_name: techreo-challenge-api
    ports:
      - "5014:5014"
    depends_on:
      - mongodb
    networks:
      - techreo-challenge-network
    environment:
      - JWT__KEY=F5BE22A679E35BA82F04D1427DBE56B8FC7301E529A1322110715467DA59E7CE
      - JWT__ISSUER=yourIssuer
      - JWT__AUDIENCE=yourAudience
      - MONGO__CONNECTIONSTRING=mongodb://mongodb:27017/banking_db

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=banking_db
      - MONGO_INITDB_ROOT_USERNAME=banking_user
      - MONGO_INITDB_ROOT_PASSWORD=banking_password
    networks:
      - techreo-challenge-network

volumes:
  mongodb_data:


networks:
  techreo-challenge-network:
    name: techreo-challenge-network
    driver: bridge
