# Use the official Node.js image to build the app
FROM node:18-alpine AS build
WORKDIR /app

# Copy the Angular project files and install dependencies
COPY package*.json ./
RUN npm install

# Copy all the project files
COPY . .

# Build the Angular app
RUN npm run build --prod

# Use NGINX to serve the Angular app
FROM nginx:alpine

# Remove the default NGINX welcome page
RUN rm /usr/share/nginx/html/index.html

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the Angular build output to NGINX's html directory
COPY --from=build /app/dist/techreo-challenge-web/browser /usr/share/nginx/html

# Expose port 80 for the frontend
EXPOSE 80
