name: Build, Scan, and Push API Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./TechreoChallenge.API
          file: ./TechreoChallenge.API/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/techreo-challenge-api:latest

      # Set up Trivy
      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v1

      # Scan Docker image for vulnerabilities
      - name: Scan Docker image
        run: trivy image ghcr.io/${{ github.repository_owner }}/techreo-challenge-api:latest

      # Push Docker image if no vulnerabilities found
      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: ./TechreoChallenge.API
          file: ./TechreoChallenge.API/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/techreo-challenge-api:latest
