name: Build, Scan, and Push API Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file ./TechreoChallenge.Api/Dockerfile --tag ghcr.io/${{ github.repository }}-api:latest

      - name: Check Docker image
        run: |
          docker images
          docker inspect ghcr.io/${{ github.repository }}-api:latest
      
      # Setun an run Trivy scan 
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/${{ github.repository }}-api:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # Push Docker image if no vulnerabilities found
      - name: Push Docker image
        if: success()
        run: docker push ghcr.io/${{ github.repository }}-api:latest
