name: Build, Scan, and Push Front-End Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image for Angular app
      - name: Build the Docker image
        run: |
          docker build ./techreo-challenge-web --file ./techreo-challenge-web/dockerfile --tag ghcr.io/${{ github.repository_owner }}/techreo-challenge-web:latest

      # Run Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/techreo-challenge-web:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Upload SARIF file
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # Push Docker image if no vulnerabilities found
      - name: Push Docker image
        if: success()
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/techreo-challenge-web:latest
